'''
Austen K. Scruggs
06/02/2020
Description: Plot data from datafame from NLLS_tmatrix_in_Mie_space script
'''
import pandas as pd
import matplotlib.pyplot as plt

directory = '/home/austen/Desktop/Recent/'

SL_DF = pd.read_csv(directory + 'SL_DF_NLLS_Tmat_Mie.txt', sep=',', header=0)
SR_DF = pd.read_csv(directory + 'SR_DF_NLLS_Tmat_Mie.txt', sep=',', header=0)


# make figures
f_font =18
t_font = 16
l_font = 14
f0, ax0 = plt.subplots(3, 3, figsize=(24, 18))
ax0[0, 0].plot(SL_DF["axis ratio"], SL_DF["n"], marker='o', color='black', ls=' ', label='SL n')
ax0[0, 0].plot(SR_DF["axis ratio"], SR_DF["n"], marker='X', color='red', ls=' ', label='SR n')
ax0[0, 0].set_title('n vs. axis ratio', fontsize=t_font)
ax0[0, 0].set_xlabel('axis ratio', fontsize=l_font)
ax0[0, 0].set_ylabel('n', fontsize=l_font)
ax0[0, 0].grid(True)
ax0[0, 0].legend(loc=1, fontsize=l_font)
ax0[0, 1].plot(SL_DF["axis ratio"], SL_DF["k"], marker='o', color='black', ls=' ', label='SL k')
ax0[0, 1].plot(SR_DF["axis ratio"], SR_DF["k"], marker='X', color='red', ls=' ', label='SR k')
ax0[0, 1].set_title('k vs. axis ratio', fontsize=t_font)
ax0[0, 1].set_xlabel('axis ratio', fontsize=l_font)
ax0[0, 1].set_ylabel('k', fontsize=l_font)
ax0[0, 1].grid(True)
ax0[0, 1].legend(loc=1, fontsize=l_font)
ax0[0, 2].plot(SL_DF["axis ratio"], SL_DF["Cext Mie"], marker='o', color='black', ls=' ', label='SL $C_{ext}$ Mie')
ax0[0, 2].plot(SR_DF["axis ratio"], SR_DF["Cext Mie"], marker='X', color='red', ls=' ', label='SR $C_{ext}$ Mie')
ax0[0, 2].plot(SL_DF["axis ratio"], SL_DF["Cext Tmat"], marker='s', color='lawngreen', ls=' ', label='SL $C_{ext}$ Tmat')
ax0[0, 2].plot(SR_DF["axis ratio"], SR_DF["Cext Tmat"], marker='^', color='blue', ls=' ', label='SR $C_{ext}$ Tmat')
ax0[0, 2].set_title('$C_{ext}$ vs. axis ratio', fontsize=t_font)
ax0[0, 2].set_xlabel('axis ratio', fontsize=l_font)
ax0[0, 2].set_ylabel('$C_{ext}$', fontsize=l_font)
ax0[0, 2].grid(True)
ax0[0, 2].legend(loc=1, fontsize=l_font)
ax0[1, 0].plot(SL_DF["axis ratio"], SL_DF["Csca Mie"], marker='o', color='black', ls=' ', label='SL $C_{sca}$ Mie')
ax0[1, 0].plot(SR_DF["axis ratio"], SR_DF["Csca Mie"], marker='X', color='red', ls=' ', label='SR $C_{sca}$ Mie')
ax0[1, 0].plot(SL_DF["axis ratio"], SL_DF["Csca Tmat"], marker='s', color='lawngreen', ls=' ', label='SL $C_{sca}$ Tmat')
ax0[1, 0].plot(SR_DF["axis ratio"], SR_DF["Csca Tmat"], marker='^', color='blue', ls=' ', label='SR $C_{sca}$ Tmat')
ax0[1, 0].set_title('$C_{sca}$ vs. axis ratio', fontsize=t_font)
ax0[1, 0].set_xlabel('axis ratio', fontsize=l_font)
ax0[1, 0].set_ylabel('$C_{sca}$', fontsize=l_font)
ax0[1, 0].grid(True)
ax0[1, 0].legend(loc=1, fontsize=l_font)
ax0[1, 1].plot(SL_DF["axis ratio"], SL_DF["Cabs Mie"], marker='o', color='black', ls=' ', label='SL $C_{abs} Mie$')
ax0[1, 1].plot(SR_DF["axis ratio"], SR_DF["Cabs Mie"], marker='X', color='red', ls=' ', label='SR $C_{abs} Mie$')
ax0[1, 1].set_title('$C_{abs}$ vs. axis ratio', fontsize=t_font)
ax0[1, 1].set_xlabel('axis ratio', fontsize=l_font)
ax0[1, 1].set_ylabel('$C_{abs}$', fontsize=l_font)
ax0[1, 1].grid(True)
ax0[1, 1].legend(loc=1, fontsize=l_font)
ax0[1, 2].plot(SL_DF["axis ratio"], SL_DF["bigG Mie"], marker='o', color='black', ls=' ', label='SL G Mie')
ax0[1, 2].plot(SR_DF["axis ratio"], SR_DF["bigG Mie"], marker='X', color='red', ls=' ', label='SR G Mie')
ax0[1, 2].plot(SL_DF["axis ratio"], SL_DF["g Tmat"], marker='s', color='lawngreen', ls=' ', label='SL G Tmat')
ax0[1, 2].plot(SR_DF["axis ratio"], SR_DF["g Tmat"], marker='^', color='blue', ls=' ', label='SR G Tmat')
ax0[1, 2].set_title('G vs. axis ratio', fontsize=t_font)
ax0[1, 2].set_xlabel('axis ratio', fontsize=l_font)
ax0[1, 2].set_ylabel('G', fontsize=l_font)
ax0[1, 2].grid(True)
ax0[1, 2].legend(loc=1, fontsize=l_font)
ax0[2, 0].plot(SL_DF["axis ratio"], SL_DF["GeoMean"], marker='o', color='black', ls=' ', label='SL Geometric Mean')
ax0[2, 0].plot(SR_DF["axis ratio"], SR_DF["GeoMean"], marker='X', color='red', ls=' ', label='SR Geometric Mean')
ax0[2, 0].set_title('Geometric Mean vs. axis ratio', fontsize=t_font)
ax0[2, 0].set_xlabel('axis ratio', fontsize=l_font)
ax0[2, 0].set_ylabel('Geometric Mean', fontsize=l_font)
ax0[2, 0].grid(True)
ax0[2, 0].legend(loc=1, fontsize=l_font)
ax0[2, 1].plot(SL_DF["axis ratio"], SL_DF["GeoStdev"], marker='o', color='black', ls=' ', label='SL Geometric Stdev')
ax0[2, 1].plot(SR_DF["axis ratio"], SR_DF["GeoStdev"], marker='X', color='red', ls=' ', label='SR Geometric Stdev')
ax0[2, 1].set_title('Geometric Standard Dev. vs. axis ratio', fontsize=t_font)
ax0[2, 1].set_xlabel('axis ratio', fontsize=l_font)
ax0[2, 1].set_ylabel('Geometric Stdev', fontsize=l_font)
ax0[2, 1].grid(True)
ax0[2, 1].legend(loc=1, fontsize=l_font)
ax0[2, 2].plot(SL_DF["axis ratio"], SL_DF["N"], marker='o', color='black', ls=' ', label='SL Number Density')
ax0[2, 2].plot(SR_DF["axis ratio"], SR_DF["N"], marker='X', color='red', ls=' ', label='SR Number Density')
ax0[2, 2].set_title('Number Density vs. axis ratio', fontsize=t_font)
ax0[2, 2].set_xlabel('axis ratio', fontsize=l_font)
ax0[2, 2].set_ylabel('Number Density', fontsize=l_font)
ax0[2, 2].grid(True)
ax0[2, 2].legend(loc=1, fontsize=l_font)
f0.suptitle('Nonlinear Least Squares Retrieved vs. Axis Ratio', fontsize=f_font)
#plt.tight_layout()
plt.savefig(directory + 'NLLS_tmat_miespace_retrieval.pdf', format='pdf')
plt.savefig(directory + 'NLLS_tmat_miespace_retrieval.png', format='png')
plt.show()

